# Generated by Django 4.1.7 on 2023-03-16 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super User')),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2023, 3, 16, 15, 34, 52, 324724), verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='email address')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=12, null=True, verbose_name='mobile number')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
