# Generated by Django 4.1.7 on 2023-03-19 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_username_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 9, 12, 35, 928322), verbose_name='date joined'),
        ),
    ]
